adminUser: admin
adminPassword: admin123

# Désactiver les ressources dépréciées
rbac:
  pspEnabled: false
  create: true

testFramework:
  enabled: false

persistence:
  enabled: true
  size: 5Gi

# Configuration Ingress pour NGINX
ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - grafana.localhost
  path: /

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server.monitoring.svc.cluster.local
        isDefault: true
      - name: Loki
        type: loki
        access: proxy
        url: http://loki.logging.svc.cluster.local:3100

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default

dashboards:
  default:
    kubernetes-cluster:
      gnetId: 7249
      revision: 1
      datasource: Prometheus
    loki-logs:
      gnetId: 13639
      revision: 2
      datasource: Loki

grafana.ini:
  auth.generic_oauth:
    enabled: true
    name: Keycloak
    client_id: grafana
    client_secret: $__env{GRAFANA_OAUTH_CLIENT_SECRET}
    scopes: openid profile email
    auth_url: http://keycloak.localhost/realms/zero-trust/protocol/openid-connect/auth
    token_url: http://keycloak.localhost/realms/zero-trust/protocol/openid-connect/token
    api_url: http://keycloak.localhost/realms/zero-trust/protocol/openid-connect/userinfo
    allow_sign_up: true
    role_attribute_path: contains(groups[*], 'admin') && 'Admin' || 'Viewer'

# Environment variables for sensitive data
env:
  GRAFANA_OAUTH_CLIENT_SECRET: "grafana-client-secret-from-keycloak"
