# Configuration pour Loki en mode single binary
deploymentMode: SingleBinary

loki:
  # Configuration pour un déploiement simple
  auth_enabled: false
  
  commonConfig:
    replication_factor: 1
  
  storage:
    type: 'filesystem'
  
  schemaConfig:
    configs:
      - from: 2020-10-24
        store: boltdb-shipper
        object_store: filesystem
        schema: v11
        index:
          prefix: index_
          period: 24h

# Désactiver les composantes enterprise
enterprise:
  enabled: false

# Configuration simple pour lab
singleBinary:
  replicas: 1
  persistence:
    enabled: true
    size: 10Gi

# Désactiver les composants non nécessaires
ingester:
  replicas: 0
distributor:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0

# Configuration Ingress
gateway:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - host: loki.localhost
        paths:
          - path: /
            pathType: Prefix

# Désactiver les métriques Grafana Agent
monitoring:
  selfMonitoring:
    enabled: false
  lokiCanary:
    enabled: false

# Test framework
test:
  enabled: false
