auth:
  adminUser: admin
  existingSecret: "keycloak-admin-secret"
  passwordSecretKey: "admin-password"

secrets:
  adminPassword: ""

service:
  type: ClusterIP
  http:
    port: 8080

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: keycloak.localhost
      paths:
        - path: /
          pathType: Prefix
  tls: []

# Resource limits for better security
resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

# Security context
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1001
  fsGroup: 1001

postgresql:
  enabled: true
  auth:
    existingSecret: "keycloak-db-secret"
    secretKeys:
      adminPasswordKey: "postgres-password"
      userPasswordKey: "user-password"
